- name: Setup Postfix
  hosts: mail-server
  tasks:
  - name: Setup Group and Users
    block:
    - name: Create services group
      ansible.builtin.group:
        name: services
        system: yes
    
    - name: Create mail account
      ansible.builtin.user:
        name: mail
        append: yes
        groups: 
          - services

    - name: Create Test Users
      ansible.builtin.user:
        name: "{{ item }}"
        password: "{{ item | password_hash('sha512') }}"
      loop:
        - alice
        - bob
        - carol
        - david
        - eve
    
    become: yes

  - name: Update & Install Packages
    block:
    - name: Update Package Lists
      ansible.builtin.apt:
        update_cache: yes

      become: yes
    
    - name: Install Packages
      ansible.builtin.apt:
        pkg:
          - postfix
          - acl 
          - mailutils

      become: yes
  
  - name: Start the Postfix service
    ansible.builtin.systemd_service:
      name: postfix
      enabled: yes
      state: started
      
    become: yes
    become_user: mail
