- name: Setup Redis
  hosts: redis-db
  become: yes
  tasks:
  - name: Update & Install Packages
    block:
    - name: Update Package Lists
      ansible.builtin.apt:
        update_cache: yes
    
    - name: Install Packages
      ansible.builtin.apt:
        pkg:
          - acl
          - redis

  - name: Configure Redis
    block:
    - name: Copy Redis Config to Server
      ansible.builtin.copy:
        src: ../redis-db/redis.conf
        dest: /etc/redis/redis.conf

    - name: Copy Redis ACL to Server
      ansible.builtin.copy:
        src: ../redis-db/users.acl
        dest: /etc/redis/users.acl

    become_user: redis

  - name: Start Redis Service
    ansible.builtin.service:
      name: redis
      enabled: yes
      state: restarted