- name: Generate Indexer Certs
  hosts: wazuh-indexer
  roles:
    - role: ../wazuh-ansible/roles/wazuh/wazuh-indexer
      perform_installation: false
  become: no
  vars:
    indexer_node_master: true
    instances:
      node1:
        name: node-1
        ip: 127.0.0.1
        role: indexer
  tags:
    - generate-certs

- name: Setup Wazuh Indexer
  hosts: wazuh-indexer
  become: yes
  become_user: root
  roles:
    - role: ../wazuh-ansible/roles/wazuh/wazuh-indexer

  vars:
    single_node: true
    indexer_network_host: 192.0.1.34
    ansible_shell_allow_world_readable_temp: true
    instances:
      node1:
        name: node-1
        ip: 127.0.0.1
        role: indexer
