- name: "Setup Wazuh Manager and Filebeat"
  hosts: manager
  roles:
    - role: ../wazuh-ansible/roles/wazuh/ansible-wazuh-manager
    - role: ../wazuh-ansible/roles/wazuh/ansible-wazuh-filebeat-oss
      filebeat_output_indexer_hosts:
      - "[INDEXER]:9200"
